version: 2

sources:
  - name: raw_data
    database: finance_db    # Your Snowflake database
    schema: finance_sch             # Schema where raw data is stored
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products